name: Deploy HTML to AWS S3
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  Europe (Stockholm): eu-north-1
  S3_BUCKET: jekaterina-html-deploy-2026
jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::208937956131:role/GitHubActionsS3DeployRole
          aws-region: ${{ env.Europe (Stockholm) }}
      - name: Deploy files to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"